# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Política de Privacidade
email: bardsoftware@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Nossa Política de Privacidade descreve como coletamos, usamos e protegemos as informações dos usuários. Coletamos dados fornecidos diretamente pelos usuários, como informações de contato e do dispositivo, bem como dados de uso do site, essenciais para o funcionamento e melhoria dos nossos serviços. Utilizamos essas informações para fornecer e melhorar nossos serviços, personalizar a experiência do usuário, garantir a segurança dos sistemas e cumprir com obrigações legais. Não compartilhamos informações pessoais com terceiros, exceto quando necessário para cumprir com obrigações legais ou proteger nossos direitos. Implementamos medidas de segurança para proteger os dados contra acesso não autorizado e outras ameaças. Os usuários têm o direito de acessar, corrigir ou excluir suas informações pessoais a qualquer momento, bastando entrar em contato conosco. Para dúvidas sobre esta Política de Privacidade, entre em contato através do e-mail bardsoftware@gmail.com.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/